### PR TITLE
sjawhar-legion-301: fix handoff data pipeline silent failure

### LINKED ISSUE #301: Handoff data pipeline silent failure — no .legion/ data written despite 40+ issues closing
## Problem

Issues #238 (knowledge injection) and #239 (learnings tracking) are closed and the handoff schema includes `learningsInjected`/`learningsHelpful` fields in all 5 workflow templates. But after 40+ issues closing since they shipped, **zero `.legion/` handoff directories exist on any issue branch**.

The handoff write commands use `|| true` (silent failure), so workers fail to write handoff data without any error.

## Impact

- Issue #240 (index evolution) is blocked — needs 20+ issues of feedback data to design the promotion/demotion algorithm
- Knowledge compounding (#218) cannot be measured or improved
- The learnings feedback loop is completely broken

## Investigation Needed

1. Why aren't handoff writes happening? Is it the CLI, the workers, or the workflow execution?
2. Are workers reaching the handoff write step at all?
3. Does the `legion handoff write` command work correctly?

## Fix

1. Remove `|| true` from handoff write commands — fail loudly if handoff write fails
2. Add a verification step: after handoff write, confirm the file exists
3. Test end-to-end: a single issue should produce `.legion/architect.json`, `.legion/plan.json`, etc.

## Labels

bug

### PR DESCRIPTION
**Pull request by sjawhar**
Closes #301

## Summary

Fix the handoff data pipeline that has been silently failing — no `.legion/` data written despite 40+ issues closing since the feature shipped.

**Root cause**: Three layers of failure:
1. **TypeScript** (`ledger.ts`): `writePhaseHandoff()`, `ensureLegionDir()`, and `writeMessage()` wrapped all operations in try-catch that swallowed errors, only logging to stderr
2. **Workflow markdown**: All 9 handoff write commands across 6 workflow files used `2>/dev/null || true` to suppress failures and exit codes
3. **`.gitignore`**: The `.legion/` directory was gitignored, preventing handoff data from being committed even when writes succeeded

**Fix**:
- Remove error-swallowing try-catch from write functions in `ledger.ts` — errors now propagate to callers
- CLI handlers catch propagated errors, print useful messages (`[handoff] Failed to write handoff: <reason>`), and exit with code 1
- CLI prints confirmation on success (`[handoff] Wrote <phase> handoff to <path>`)
- Removed `2>/dev/null || true` from all 9 handoff write commands across 6 workflow files (architect, plan, implement×2, test, review, retro×2)
- Added verification step after each handoff write checking file existence
- Updated documentation to reflect fail-loudly behavior
- Removed `.legion/` from `.gitignore` so handoff data is committed to issue branches
- Read functions intentionally keep graceful degradation (reads may happen before earlier phases write)
- 4 new tests covering success confirmation output, write failure propagation with non-zero exit codes

### CODE REVIEW

File: packages/daemon/src/cli/index.ts [hunk 1]
```diff
@@ -987,12 +987,17 @@ export const handoffCommand = defineCommand({
           }
           const data = parseHandoffData(rawData);
           writePhaseHandoff(workspaceDir, phase, data);
+          const filePath = path.join(workspaceDir, ".legion", `${phase}.json`);
```
Comment (sjawhar) [inline packages/daemon/src/cli/index.ts]: **[P3]:** This path is constructed manually rather than importing `PHASE_FILE_NAMES[phase]` from schema. Currently correct since all phases map to `${phase}.json`, but creates a minor divergence point. Consider importing the constant for consistency — though this is cosmetic since the actual file write uses the canonical path through `writePhaseHandoff`.
