### PR TITLE
sjawhar-legion-62: include CI status in collected state output

### LINKED ISSUE #62: State machine: include CI status in collected state output
## Problem

The state machine (`/state/collect`) reports `hasPr` and `prIsDraft` but does not include CI check status. The controller currently has no signal for whether CI is passing or failing on a PR.

This means:
- The controller can advance a PR to review even when CI is red
- The reviewer has to independently check CI (added in review workflow as a workaround)
- The implementer is supposed to wait for CI before exiting, but if they don't, nothing catches it

## Proposal

Add a `ciStatus` field to the collected state output alongside the existing PR fields:

```typescript
// In CollectedIssueState
ciStatus: "passing" | "failing" | "pending" | null; // null if no PR or couldn't check
```

This would allow the decision logic to:
- Block `dispatch_reviewer` when CI is failing (re-dispatch implementer instead)
- Include CI status in the `suggestedAction` reasoning
- Give the controller a signal to act on without independently querying GitHub

## Context

During a controller session, multiple PRs were advanced through review and retro with failing CI (ruff format, typecheck errors). The failures weren't caught until a human pointed them out. The implement and review workflows have been updated to check CI, but the state machine should also surface this as a first-class signal.

### PR DESCRIPTION
**Pull request by sjawhar**
Closes #62

## Summary

Add `ciStatus` field to the state machine's collected output so the controller can gate reviewer dispatch and retro transitions on CI health.

### Changes

- **types.ts**: Add `CiStatusLiteral` type (`passing | failing | pending`), new action types (`resume_implementer_for_ci_failure`, `retry_ci_check`), `needsCiStatus` getter, `ciStatus` field in `FetchedIssueData`/`IssueStateDict`/`IssueState`
- **fetch.ts**: Add `mapCiRollupState()` mapping, `getCiStatusBatch()` batched GraphQL function (same pattern as `getPrDraftStatusBatch`), wire CI status through `enrichParsedIssues()` as third parallel operation
- **decision.ts**: Add optional `ciStatus` parameter to `suggestAction()` (backward compatible), CI gating in NEEDS_REVIEW (`prIsDraft` takes precedence), both new actions in `ACTION_TO_MODE`, `buildIssueState` passes and returns `ciStatus`
- **Tests**: 32 new tests covering CI gating behavior, batch fetching, enrichment wiring, and regression scenarios
- **AGENTS.md**: Updated state machine table and data flow docs

### CI Gating Logic

| Scenario | CI Status | Action |
|----------|-----------|--------|
| worker-done + ready PR | failing | `resume_implementer_for_ci_failure` |
| worker-done + ready PR | pending | `retry_ci_check` |
| worker-done + ready PR | passing/null | `transition_to_retro` |
| no worker-done + has PR | failing | `resume_implementer_for_ci_failure` |
| no worker-done + has PR | pending | `retry_ci_check` |
| no worker-done | passing/null | `dispatch_reviewer` |

### Verification

- ✅ 677 tests pass (0 failures)
- ✅ `tsc --noEmit` clean
- ✅ `biome check` clean

Closes #62

### CODE REVIEW

File: packages/daemon/src/state/types.ts [hunk 1]
```diff
@@ -305,6 +318,10 @@ export function createParsedIssue(
         this.prRef !== null
       );
     },
+
```
Comment (sjawhar) [inline packages/daemon/src/state/types.ts]: **[P3]:** This getter is intentionally broader than `needsPrStatus` above (doesn't require `worker-done`). Consider adding a comment explaining the asymmetry — e.g. `// Broader than needsPrStatus: CI should be checked before dispatching reviewer (no worker-done) AND before transitioning to retro (worker-done)`. Prevents someone "fixing" it to match `needsPrStatus` in the future.
