### PR TITLE
sjawhar-legion-398: add legion poll command for compact state machine summary

### LINKED ISSUE #398: feat(cli): add `legion poll` command for compact state machine summary
## Problem

The controller currently uses a broken `gh project item-list | /state/collect` pipeline that truncates at 30 items on a 214-item board. Even with the fix to use `POST /state/fetch-and-collect`, the raw JSON response is huge and wastes context window.

## Solution

Add a `legion poll` CLI command that:
1. Calls `POST /state/fetch-and-collect` internally
2. Returns a **summarized** view optimized for controller context windows

### Default output (human/controller-friendly)

```
ACTIONABLE (7):
  dispatch_implementer:
    #9891  In Progress  "QA pipeline prototype"
  dispatch_architect:
    #6657  Backlog      "WhatsApp country code dropdown"
    #6831  Backlog      "Bitwarden credentials loading"
  dispatch_planner:
    #6683  Todo         "Greenhouse form persistence"

BLOCKED (2):
  #9948  user-input-needed  "Zendesk ticketing"
  #5628  worker-active (stale)  "Profile pic storage"

SUMMARY:
  Done: 45 | Icebox: 8 | Scrapped: 15 | In Progress (with worker): 12 | Skip: 127
```

### `--json` flag

Full raw `/state/fetch-and-collect` response for programmatic use.

## Design

- Uses existing `POST /state/fetch-and-collect` endpoint — no new daemon changes
- Groups actionable items by `suggestedAction` prefix
- Filters non-actionable items into summary counts
- Compact enough for a controller to consume in one poll without burning context

## Scope

- New CLI command in `packages/daemon/src/cli/index.ts` (citty `defineCommand`)
- Formatting logic for the summary view
- `--json` passthrough flag

Independent of V2 — makes V1 work better now.

### PR DESCRIPTION
**Pull request by sjawhar**
Closes #398

## Summary

Add a `legion poll` CLI command that calls `POST /state/fetch-and-collect` internally and returns a compact, controller-friendly summary of actionable issues — reducing context window usage from raw JSON to a few lines.

### Output format
```
ACTIONABLE (7):
  dispatch_implementer:
    #42  In Progress  "Fix widget alignment"
  dispatch_planner:
    #44  Todo  "Redesign settings page"

BLOCKED (2):
  #50  user-input-needed  "Zendesk ticketing"
  #51  worker-active (stale)  "Profile pic storage"

SUMMARY:
  Done: 45 | Icebox: 8
```

### Changes
- **New:** `packages/daemon/src/cli/poll-formatter.ts` — pure formatter module (no I/O), categorizes issues into ACTIONABLE/BLOCKED/SUMMARY
- **New:** `packages/daemon/src/cli/__tests__/poll-formatter.test.ts` — 5 tests with realistic state machine fixtures
- **Modified:** `packages/daemon/src/cli/index.ts` — `cmdPoll()`, `pollCommand`, registered in `mainCommand.subCommands`
- **Modified:** `packages/daemon/src/daemon/server.ts` — added `titles` map to fetch-and-collect response (backward-compatible additive field)
- **Modified:** `packages/daemon/src/state/types.ts` — exported `IssueStateDict` for formatter type safety

### Design decisions
- Blocking conditions (user-input-needed, stale worker-active) are checked BEFORE suggestedAction to correctly classify issues the state machine gives actionable actions to (e.g., `remove_worker_active_and_redispatch`)
- Output is deterministically sorted (action groups alphabetically, summary alphabetically) for stable controller consumption
- Backend hardcoded to `github` since `fetch-and-collect` only supports that currently
- `--json` flag passes through raw fetch-and-collect response for programmatic use

### CODE REVIEW

**Comment by sjawhar** [comment]
## Behavioral Test Results

### Summary
**PASS** — 6/6 acceptance criteria verified

### Results
| Criterion | Status | Evidence |
|-----------|--------|----------|
| `legion poll` CLI command exists with `--help` | ✅ | `bun run packages/daemon/src/cli/index.ts poll --help` outputs usage with TEAM positional arg and `--json` boolean option |
| Calls `POST /state/fetch-and-collect` internally | ✅ | `legion poll "trajectory-labs-pbc/2"` returned 195 issues from the live daemon (matching `curl -s /state/fetch-and-collect -X POST` which returns `{"issues": ...}` with 195 entries) |
| Default output: ACTIONABLE grouped by suggestedAction | ✅ | Output shows `ACTIONABLE (24):` with groups `dispatch_architect:` (17 items), `dispatch_implementer:` (1), `dispatch_planner:` (5), `rebase_pr:` (1). Issues formatted as `#NUMBER  STATUS` |
| Default output: BLOCKED section | ✅ | Output shows `BLOCKED (10):` with 8 `user-input-needed` and 2 `worker-active (stale)` entries. Verified by code inspection: blocking conditions checked BEFORE suggestedAction (`poll-formatter.ts:28-44`), correctly classifying issues with non-skip actions (e.g., `relay_user_feedback`) as blocked |
| Default output: SUMMARY counts | ✅ | Output shows `SUMMARY: ": 35 \| Backlog: 3 \| Done: 60 \| Icebox: 49 \| Scrapped: 13 \| Todo: 1"`. Entries sorted alphabetically for deterministic output |
| `--json` flag returns raw response | ✅ | `legion poll "trajectory-labs-pbc/2" --json \| jq 'keys'` returns `["issues"]` with 195 entries parseable by jq |

**Titles:** The daemon on main doesn't include the `titles` field in fetch-and-collect response (PR adds this in server.ts). Verified via unit tests that titles display in quotes when available: `expect(output).toContain('#42  In Progress  "Fix widget alignment"')`. CLI gracefully falls back to no titles via `data.titles ?? {}`.

**CI note:** Confirmed `statusCheckRollup: []` — CI never triggered on PR #402.

### Local CI Substitute (since CI didn't trigger)
| Check | Status | Evidence |
|-------|--------|----------|
| Biome lint | ✅ | `bunx biome check src/` — `Checked 80 files in 98ms. No fixes applied.` |
| TypeScript | ✅ | `bunx tsc --noEmit` — no output (clean) |
| Unit tests | ✅ | `bun test` — 729 pass, 1 fail. The 1 failure is pre-existing: `daemon entry > passes controller env vars to adapter.start on startup` (confirmed in implementer handoff). Poll-specific tests: 5/5 pass |

### Test Quality Critique
**Good:**
- Tests use realistic state machine fixtures — the blocked test correctly uses non-skip actions (`relay_user_feedback`, `remove_worker_active_and_redispatch`) matching actual state machine behavior, validating the critical blocking-before-actionable precedence
- Pure formatter module with no I/O makes tests fast and deterministic
- 5 test cases covering: actionable grouping with titles, blocked detection, summary counts, empty section omission, null source fallback

**P2 — Missing test coverage:**
- No integration tests for `cmdPoll()` — the network call, error handling (`CliError` wrapping), and JSON passthrough are untested
- No test for `isBlocked: true` path (only `user-input-needed` and stale `worker-active` are tested)
- No test for empty issues input (`formatPollOutput({}, {})`)
- No test for deterministic sort order stability with many action groups

### Documentation Feedback
- PR description is clear and comprehensive — design decisions documented inline
- No README/usage docs updated, which is appropriate for an operator CLI command
- In-code comments explain the "why" of blocking-before-actionable precedence

### Observations
- Empty status strings from the project board render as `": 35"` in SUMMARY — minor UX issue; consider displaying as `(no status): 35`
- Error handling with invalid team shows stack trace rather than clean error message (consistent with other commands but suboptimal UX for operators)

### Config Compliance
- require_specific_task: false — N/A (default)
- require_taiga_evidence: false — N/A (default)

**Comment by sjawhar** [comment]
## Review Summary

**CRITICAL (P1):** 0 issues
**IMPORTANT (P2):** 0 issues
**MINOR (P3):** 3 suggestions

**Verdict: Approved to merge** ✅

---

### Review Process

5-agent parallel review conducted:

| Agent | Verdict | Notes |
|-------|---------|-------|
| Goal & Constraint Verification (Oracle) | PASS* | Initially flagged SUMMARY semantics as incomplete — dismissed after verifying implementation matches spec example exactly |
| QA Execution | PASS | 5/5 formatter tests, biome clean, tsc clean, 729/730 suite (1 pre-existing failure in `index.test.ts`) |
| Code Quality (Oracle) | PASS* | Initially flagged hardcoded github backend — dismissed because issue explicitly constrains this |
| Security Review (Oracle) | PASS | Low-severity terminal escape concern noted (non-blocking) |
| Context Mining | PASS | No missed requirements; response shape change is backward-compatible |

*Agents 1 and 3 initially returned FAIL but their blocking issues were assessed against the actual spec and found to be misinterpretations of the requirements.

### Key Findings

**Architecture & Design:**
- Blocking-before-actionable precedence in the formatter is a deliberate and well-documented design choice. The test at line 61-66 of poll-formatter.test.ts explicitly validates that `relay_user_feedback` and `remove_worker_active_and_redispatch` actions are correctly classified as BLOCKED when the corresponding labels are present. This matches the issue spec's example output.
- Pure formatter module with no I/O is a clean separation of concerns.
- Title extraction refactored to avoid double extraction — improvement over the plan.
- Additive `titles` field on fetch-and-collect response is backward-compatible (verified: no existing tests assert on successful response body).

**CI Status:** lint ✅ | test ✅ | typecheck ✅ — all passing.

### P3 Observations (Non-Blocking)

1. **Empty status strings** — Status `""` from the project board renders as `: 35` in SUMMARY. Consider `summary[issue.status || "(no status)"] = ...` for cleaner UX. (Also noted by tester.)
2. **Test coverage gap for `isBlocked` path** — `categorizeIssues` handles `issue.isBlocked` at line 41-43, but no test exercises this branch. Minor coverage gap.
3. **Terminal escape injection (security, low severity)** — Issue titles from GitHub are printed verbatim. In theory, attacker-controlled titles with ANSI escape sequences could manipulate operator terminal output. This is a localhost CLI for trusted operators, so risk is very low.

### Evidence
- CI status: lint pass (7s), test pass (44s), typecheck pass (13s)
- All 5 poll-formatter unit tests pass with 15 assertions
- Full suite: 729/730 (1 pre-existing failure in daemon entry test, unrelated to poll changes)
- No LSP diagnostics in changed files

File: packages/daemon/src/cli/poll-formatter.ts [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+        issueId,
+        action: issue.suggestedAction,
+        status: issue.status,
+        source: issue.source,
+      });
+      continue;
+    }
+
+    // Non-actionable, non-blocked — count in summary
+    summary[issue.status] = (summary[issue.status] ?? 0) + 1;
```
Comment (sjawhar) [inline packages/daemon/src/cli/poll-formatter.ts:58]: **[P3/MINOR]:** Empty status strings from the project board will render as `": 35"` in SUMMARY. Consider `summary[issue.status || "(no status)"] = ...` for cleaner UX.

File: packages/daemon/src/cli/poll-formatter.ts [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+      continue;
+    }
+
+    if (issue.labels.includes("worker-active") && !issue.hasLiveWorker) {
+      blocked.push({ issueId, reason: "worker-active (stale)", source: issue.source });
+      continue;
+    }
+
+    if (issue.isBlocked) {
+      blocked.push({ issueId, reason: "blocked", source: issue.source });
```
Comment (sjawhar) [inline packages/daemon/src/cli/poll-formatter.ts:42]: **[P3/MINOR]:** No test exercises the `issue.isBlocked` branch. Consider adding a test case with `isBlocked: true` to verify issues land in BLOCKED with reason `"blocked"`.
