### PR TITLE
sjawhar-legion-65: State machine hardening — fix 8 pre-existing issues

### LINKED ISSUE #65: State machine hardening: pre-existing issues surfaced during testing gate review
## Context

During the red-team review of the behavioral testing gate (#63), four independent reviewers surfaced pre-existing issues in the state machine and skill layer that are NOT caused by the testing gate changes but should be addressed.

### P1 — Can cause incorrect behavior

**11. `In Progress + hasPr + no live worker + no worker-done → skip` deadlock**

`packages/daemon/src/state/decision.ts` — If an implementer dies before adding `worker-done` (but after opening a PR), the state machine returns `skip` and the issue is stuck forever. Also affects quality gate rollback: after the controller moves an issue back to In Progress, if the controller restarts before dispatching the implementer, the next loop sees `hasPr=true` + no signals and returns `skip`.

**Suggested fix:** Either dispatch a fresh implementer when `In Progress + hasPr + no worker-done + no live worker` (instead of `skip`), or encode "quality gate failed" as a label so recovery is deterministic after controller restarts.

### P2 — Should fix

**12. `needs-approval` is a global freeze**

`packages/daemon/src/state/decision.ts:143-147` — The `needs-approval` check in `buildIssueState()` fires regardless of status. If a `needs-approval` label leaks (not cleaned up after approval), it can freeze any status. Should be scoped to Backlog/Todo only, or cleaned up aggressively.

**13. Retro completion is underspecified**

The state machine requires `worker-done` in Retro to dispatch the merger, but no workflow specifies who adds it after `/legion-retro`. The Retro status also suggests `resume_implementer_for_retro` whenever any live worker exists, which can spam prompts every controller loop.

**14. No `transition_to_done` in state machine**

After merge, the issue reaches Done only via backend side-effects (GitHub auto-close, Linear automation). If that side-effect doesn't fire, the controller has no encoded path to Done. Should either add a `transition_to_done` action or document the reliance on backend automation explicitly.

**15. `sessionId` for `skip` action maps to `implement` mode**

`packages/daemon/src/state/decision.ts:110-132` — `ACTION_TO_MODE` maps `skip` to `WorkerMode.IMPLEMENT`, so the `sessionId` in collected state becomes the implementer session even when the live worker is a tester or reviewer. Any controller logic using `sessionId` during `skip` handling is at risk of targeting the wrong session.

**16. Implement workflow references undocumented tools**

`.opencode/skills/legion-worker/workflows/implement.md` references `task_create`, `task_claim_next`, `task_update`, `task_list`, `background_task`, and `/analyze`, but none of these are documented in `.opencode/skills/AGENTS.md` or any provided skills-layer docs.

**17. `worker-active` cleanup inconsistent across workflows**

`.opencode/skills/legion-worker/SKILL.md` requires removing `worker-active` on exit. Implement and test workflows do this explicitly, but architect, plan, and review workflows don't include the removal command. Risk: orphaned `worker-active` labels trigger `remove_worker_active_and_redispatch` on next controller loop.

**18. Merge workflow "exit without adding labels" + reliance on auto-close is fragile**

`.opencode/skills/legion-worker/workflows/merge.md:79-81` says "exit without adding a label" and relies on PR merge auto-closing the issue. But the documented lifecycle is status-driven to Done, and the state-machine doc shows no post-merge transition. If auto-close doesn't fire, the issue is stranded in Retro.

## Suggested approach

- Items 11, 15 are state machine code changes
- Items 12, 13, 14, 18 are decision logic + documentation
- Items 16, 17 are workflow file fixes
- Consider adding a "label invariants per status" table to the controller skill

### PR DESCRIPTION
**Pull request by sjawhar**
Implements sjawhar-legion-65

## Summary

Fixes 8 pre-existing issues (P1 + P2) in the state machine decision logic and worker skill files, surfaced during the testing gate review (#63).

### P1 — Incorrect behavior
- **Item 11**: Fixed In Progress deadlock when worker dies after PR creation — now dispatches fresh implementer instead of returning `skip`
- **Item 15**: Fixed `sessionId` for `skip` actions — uses actual `workerMode` (gated on `hasLiveWorker`) instead of defaulting to implement mode

### P2 — Should fix
- **Item 12**: Scoped `needs-approval` check to Backlog/Todo only — leaked label no longer freezes other statuses
- **Item 13**: Fixed Retro live worker spam — returns `skip` instead of `resume_implementer_for_retro` every controller loop
- **Item 14/18**: Added `transition_to_done` action type + explicit issue close in merge workflow (replaces fragile auto-close reliance)
- **Item 16**: Documented undocumented tools (`task_create`, `task_claim_next`, etc.) in implement workflow
- **Item 17**: Ensured `worker-active` label is removed in all blocking/failure exit paths (architect, plan, merge workflows)

### Verification
- 677 tests pass, 0 fail
- tsc: 0 type errors
- biome: clean

Also includes mechanical fixes for `ciStatus: null` field additions from #62 CI status types.

Closes #65

### CODE REVIEW

File: packages/daemon/src/state/fetch.ts [hunk 1]
```diff
@@ -279,6 +311,158 @@ export async function getPrDraftStatusBatch(
...
+ * Uses statusCheckRollup on the latest commit of each PR.
+ * Batches all PRs across all repositories into one API call.
+ * Retries up to 3 times with exponential backoff on failure.
+ *
+ * @param prRefs - Dict mapping issue_id to GitHubPRRef
+ * @param runner - Command runner for testing
+ * @returns Dict mapping issue_id to CI status
+ * @throws GitHubAPIError if GraphQL query fails after retries
+ */
+export async function getCiStatusBatch(
```
Comment (sjawhar) [inline packages/daemon/src/state/fetch.ts]: **[P2 — IMPORTANT]:** `getCiStatusBatch` duplicates ~140 lines of boilerplate from `getPrDraftStatusBatch` — repo grouping, alias maps, GraphQL query building, retry loop with exponential backoff, JSON response parsing, and safe object navigation are nearly identical. Consider extracting a shared `batchGraphqlQuery()` helper that accepts a query-part builder and response-value extractor, reducing both functions to ~30 lines each. Not blocking, but the next function that needs batch GraphQL will compound this.

File: packages/daemon/src/state/fetch.ts [hunk 2]
```diff
@@ -318,6 +510,18 @@ export async function enrichParsedIssues(
         }
       }
     })(),
+    (async () => {
+      if (Object.keys(ciRefsForStatus).length === 0) {
+        return;
+      }
+      try {
+        ciStatusMap = await getCiStatusBatch(ciRefsForStatus, runner);
+      } catch {
```
Comment (sjawhar) [inline packages/daemon/src/state/fetch.ts]: **[P3 — MINOR]:** `enrichParsedIssues` now makes two separate GraphQL calls in parallel (`getPrDraftStatusBatch` + `getCiStatusBatch`), both hitting the same GitHub API with the same set of PR refs. These could be combined into a single GraphQL query that fetches both `isDraft` and `commits(last:1) { nodes { commit { statusCheckRollup { state } } } }` in one round-trip, halving API calls. Low priority since they already run in parallel via `Promise.all`.
