### PR TITLE
sjawhar-legion-172: fix codebase indexer location and scanner exclusions

### LINKED ISSUE #172: Codebase indexer writes to tracked workspace dir and scans vendored JS in .venv
## Bug

The `CodebaseIndexManager` writes `.legion/daemon/index.json` to the daemon's `--workspace` path. Two problems:

### 1. Index location
The index is written to the repo working tree (e.g. `/home/ubuntu/client-repo/default/.legion/daemon/index.json`), which shows up as untracked in `jj status` / `git status`. Worker workspaces are all under `~/.local/share/legion/workspaces/`, so the index isn't even in a location any worker can reference.

The index should either:
- Be written to `~/.local/share/legion/` alongside the workspaces
- Or `.legion/` should be added to the repo's `.gitignore` by the daemon on startup

### 2. Exclusion list for scanner
The dependency graph scanner picks up vendored JavaScript inside Python packages (`.venv/lib/python3.13/site-packages/basedpyright/`, `inspect_ai/_view/www/`, React, child_process, etc.). The resulting 3.2MB index is mostly noise.

The scanner needs an exclude list — at minimum: `.venv/`, `node_modules/`, `__pycache__/`, `.git/`.

### Source
- `packages/daemon/src/index/manager.ts` — `CodebaseIndexManager`
- `packages/daemon/src/index/graph.ts` — `buildDependencyGraph()`
- `packages/daemon/src/index/persistence.ts` — `writeCodebaseIndex()`

### PR DESCRIPTION
**Pull request by sjawhar**
Closes #172

## Summary

- **Index location**: `resolveCodebaseIndexPath()` now always writes to the XDG state directory (`~/.local/state/legion/legions/{projectId}/index.json`) instead of polluting the tracked workspace at `{legionDir}/.legion/daemon/index.json`. This was already the fallback path — we just removed the `legionDir` branch that was writing into the repo working tree.

- **Scanner exclusions**: Added `.venv`, `venv`, `__pycache__`, and `.legion` to the `SKIP_DIRS` set in the dependency graph walker. The 3.2MB index caused by scanning vendored JS inside Python packages is eliminated.

- **Tests**: 3 new tests for `listSourceFiles` covering the new exclusions (top-level, pre-existing dirs, nested dirs).

### CODE REVIEW

File: packages/daemon/src/daemon/index.ts [hunk 1]
```diff
@@ -55,10 +55,6 @@ export interface DaemonHandle {
 }
 
 function resolveCodebaseIndexPath(config: DaemonConfig, legionId: string): string {
-  if (config.legionDir) {
-    return path.join(config.legionDir, ".legion", "daemon", "index.json");
-  }
-
   return path.join(config.paths.forLegion(legionId).legionStateDir, "index.json");
```
Comment (sjawhar) [inline packages/daemon/src/daemon/index.ts]: **P3 (minor):** The `resolveCodebaseIndexPath` function is now a single-line wrapper. No test regression since the removed branch was the buggy path — but if future logic is added here, consider adding a unit test.
